// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnad7EMq2Hx8nPJYhATk9TbcD6z4ihSM',
    appId: '1:516167677061:web:46856298afed56047425ec',
    messagingSenderId: '516167677061',
    projectId: 'recipeai-89d8b',
    authDomain: 'recipeai-89d8b.firebaseapp.com',
    storageBucket: 'recipeai-89d8b.firebasestorage.app',
    measurementId: 'G-D35YDQ8X1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYMwMbkhDGzE74nLeqDlDk1VQMiIATho',
    appId: '1:516167677061:android:bc4def5e53d248da7425ec',
    messagingSenderId: '516167677061',
    projectId: 'recipeai-89d8b',
    storageBucket: 'recipeai-89d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ6-nYQ9ulbzMG7iNGEyM_I5qgc8EtG-Y',
    appId: '1:516167677061:ios:2f60fb3d106231b77425ec',
    messagingSenderId: '516167677061',
    projectId: 'recipeai-89d8b',
    storageBucket: 'recipeai-89d8b.firebasestorage.app',
    iosBundleId: 'com.example.recipeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ6-nYQ9ulbzMG7iNGEyM_I5qgc8EtG-Y',
    appId: '1:516167677061:ios:2f60fb3d106231b77425ec',
    messagingSenderId: '516167677061',
    projectId: 'recipeai-89d8b',
    storageBucket: 'recipeai-89d8b.firebasestorage.app',
    iosBundleId: 'com.example.recipeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJnad7EMq2Hx8nPJYhATk9TbcD6z4ihSM',
    appId: '1:516167677061:web:4a6477ba876a356f7425ec',
    messagingSenderId: '516167677061',
    projectId: 'recipeai-89d8b',
    authDomain: 'recipeai-89d8b.firebaseapp.com',
    storageBucket: 'recipeai-89d8b.firebasestorage.app',
    measurementId: 'G-YNVYQK8H8W',
  );
}
