import 'app_strings.dart';

/// Canonical multi-select options for profile (diet styles + common allergens).
class DietAllergyOptions {
  DietAllergyOptions._();

  /// Matches [AppStrings.dietOptions] for the questionnaire but allows several at once.
  static List<String> get dietMultiSelectOptions => [
        ...AppStrings.dietOptions.where((s) => s != AppStrings.noRestrictions),
        'Halal',
        'Kosher',
      ];

  static const List<String> commonAllergens = [
    'Milk / dairy',
    'Eggs',
    'Fish',
    'Shellfish',
    'Peanuts',
    'Tree nuts',
    'Wheat / gluten',
    'Soy',
    'Sesame',
    'Mustard',
    'Sulfites',
  ];

  static const String medicalDisclaimer =
      'Recipes are generated by AI for inspiration only. '
      'They are not verified for food allergies or medical diets. '
      'Always check ingredients and labels yourself if you have severe allergies or dietary requirements.';
}
